const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  AlignmentType, HeadingLevel, BorderStyle, WidthType, ShadingType, PageNumber, Footer, ImageRun } = require("docx");
const ARIAL = "Arial";
const FIGDIR = "/mnt/user-data/uploads";
const FIGDIR2 = require("path").join(__dirname, "figs");  // writable, for locally-generated figures
// True pixel dimensions (measured with PIL) — the byte-offset reader was unreliable on these files
const PNG_DIMS = {
  "figure_1_study_design.png":[3729,2412],
  "figure_S1_animal_flow.png":[1465,1364],
  "auc_permutation_null.png":[1861,1220],
  "cv_auc_forest.png":[2535,1566],
  "dsi4_wt_ko_trajectory.png":[2670,1470],
  "mixed_effects_trajectories.png":[4017,2246],
  "pac_full_comodulogram_matrix.png":[2742,1161],
  "pac_power_confound.png":[2112,1347],
  "pac_scekic_replication_summary.png":[4468,2660],
  "prespecified_beta_signflip.png":[3870,1485],
  "prespecified_rem_td_ratio.png":[3472,1494],
  "roc_key_features.png":[1609,1694],
  "staging_sensitivity_heatmap.png":[3342,1377],
  "state_separation_diagnostic.png":[1609,1451],
  "sleep_state_validation_motion.png":[2179,899],
  "state_transition_heatmap.png":[2852,1902]
};
// Embed a figure centered, scaled to a target display width in points (max ~460pt page width)
function figure(file, widthPt){
  let p = require("path").join(FIGDIR, file);
  if(!fs.existsSync(p)){ const p2 = require("path").join(FIGDIR2, file); if(fs.existsSync(p2)) p = p2; }
  if(!fs.existsSync(p) || !PNG_DIMS[file]){ return new Paragraph({spacing:{after:80},children:[new TextRun({text:"[missing figure: "+file+"]",italics:true,color:"AA0000"})]}); }
  const buf = fs.readFileSync(p);
  const [w,h] = PNG_DIMS[file];
  const targetW = widthPt || 430;            // points
  const targetH = Math.round(targetW * h / w);
  return new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:120,after:40},
    children:[new ImageRun({type:"png", data:buf, transformation:{width:targetW, height:targetH}})]});
}
function h1(t){return new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun(t)]});}
function h2(t){return new Paragraph({heading:HeadingLevel.HEADING_2,children:[new TextRun(t)]});}
function para(t){return new Paragraph({spacing:{after:160,line:276},children:[new TextRun(t)]});}
function rich(runs){return new Paragraph({spacing:{after:160,line:276},children:runs});}
function todo(t){return new Paragraph({spacing:{after:160,line:276},shading:{type:ShadingType.CLEAR,fill:"FFF2CC"},children:[new TextRun({text:"[TODO] "+t,italics:true,color:"7F6000"})]});}
function ph(t){return new Paragraph({spacing:{after:160,line:276},shading:{type:ShadingType.CLEAR,fill:"E2EFDA"},children:[new TextRun({text:"[PLACEHOLDER] "+t,italics:true,color:"375623"})]});}
function meta(l,v){return new Paragraph({spacing:{after:60},children:[new TextRun({text:l+": ",bold:true}),new TextRun(v)]});}
const bd={style:BorderStyle.SINGLE,size:1,color:"CCCCCC"};const bds={top:bd,bottom:bd,left:bd,right:bd};
const hdr=["Feature","TP","WT","KO","Cohen's d [95% CI]","p","q (FDR)"];
const rows=[
["REM Theta/Delta Ratio","3m","1.543","1.519","-0.04 [-0.83, 1.62]","0.331","0.603"],
["REM Theta/Delta Ratio","4m","0.784","1.415","1.97 [1.12, 3.81]","0.007","0.047 *"],
["REM Theta/Delta Ratio","9m","1.458","1.785","0.91 [-0.37, 4.03]","0.114","0.229"],
["REM Theta/Delta Ratio","12m","2.124","1.732","-0.67 [-3.98, 1.45]","0.686","0.962"],
["REM Relative Theta","3m","0.318","0.347","0.78 [-0.20, 2.52]","0.112","0.229"],
["REM Relative Theta","4m","0.244","0.309","1.50 [0.65, 2.84]","0.028","0.113"],
["REM Relative Theta","9m","0.349","0.395","2.63 [1.39, 6.61]","0.038","0.127"],
["REM Relative Theta","12m","0.352","0.379","0.74 [-0.98, 3.09]","0.486","0.747"],
["Wake Relative Beta","3m","0.138","0.118","-0.42 [-1.62, 0.56]","0.480","0.747"],
["Wake Relative Beta","4m","0.091","0.166","1.26 [0.86, 2.27]","0.005","0.047 *"],
["Wake Relative Beta","9m","0.126","0.131","0.14 [-1.48, 2.08]","0.914","0.962"],
["Wake Relative Beta","12m","0.152","0.122","-2.23 [-6.73, -1.05]","0.114","0.229"],
["Sleep Spindle Duration (s)","3m","1.021","0.936","-1.34 [-3.02, -0.40]","0.022","0.108"],
["Sleep Spindle Duration (s)","4m","0.851","0.859","0.06 [-1.10, 1.14]","1.000","1.000"],
["Sleep Spindle Duration (s)","9m","0.999","1.020","0.09 [-1.31, 1.92]","0.914","0.962"],
["Sleep Spindle Duration (s)","12m","0.877","0.864","-0.16 [-2.27, 1.75]","0.886","0.962"],
["REM Relative Beta","3m","0.151","0.142","-0.19 [-1.27, 0.85]","0.791","0.962"],
["REM Relative Beta","4m","0.108","0.159","1.27 [0.90, 2.61]","0.003","0.047 *"],
["REM Relative Beta","9m","0.141","0.139","-0.09 [-1.95, 1.73]","0.762","0.962"],
["REM Relative Beta","12m","0.158","0.135","-1.90 [-5.56, -0.71]","0.114","0.229"]];
const cw=[2400,600,900,900,2400,1080,1080];
function cell(t,h,w){return new TableCell({borders:bds,width:{size:w,type:WidthType.DXA},shading:h?{fill:"D5E8F0",type:ShadingType.CLEAR}:undefined,margins:{top:60,bottom:60,left:100,right:100},children:[new Paragraph({spacing:{after:0},children:[new TextRun({text:t,bold:h,size:18,font:ARIAL})]})]});}
const table1=new Table({width:{size:9360,type:WidthType.DXA},columnWidths:cw,rows:[new TableRow({tableHeader:true,children:hdr.map((t,i)=>cell(t,true,cw[i]))}),...rows.map(r=>new TableRow({children:r.map((c,i)=>cell(c,false,cw[i]))}))]});

// Generic table builder: header array, rows (array of arrays), and column widths (DXA)
function makeTable(headers, datarows, colw){
  const total = colw.reduce((a,b)=>a+b,0);
  return new Table({width:{size:total,type:WidthType.DXA},columnWidths:colw,rows:[
    new TableRow({tableHeader:true,children:headers.map((t,i)=>cell(t,true,colw[i]))}),
    ...datarows.map(r=>new TableRow({children:r.map((cc,i)=>cell(cc,false,colw[i]))}))
  ]});
}
function tcap(t){return new Paragraph({spacing:{before:200,after:60},children:[new TextRun({text:t,bold:true})]});}

const c=[];
c.push(new Paragraph({spacing:{after:240},children:[new TextRun({text:"A biphasic trajectory of cortical and hippocampal network dysfunction during REM sleep in C9orf72-deficient mice",bold:true,size:32,font:ARIAL})]}));
c.push(rich([new TextRun({text:"Running title: ",bold:true}),new TextRun("REM network dysfunction trajectory in C9orf72 mice")]));
c.push(new Paragraph({spacing:{after:60,before:160},children:[new TextRun({text:"Belay [Surname]\u00B9, Tewolde Teklu\u00B2*, Haben Girmay Yhdego\u00B3, [additional authors]",size:22})]}));
c.push(para("\u00B9 Tanz Centre for Research in Neurodegenerative Diseases, University of Toronto, Toronto, Ontario, Canada"));
c.push(para("\u00B2 [Department], Axum University, Axum, Ethiopia"));
c.push(para("\u00B3 [Affiliation]"));
c.push(rich([new TextRun({text:"*Corresponding author. Email: [email]",italics:true})]));
c.push(meta("Manuscript type","Original Article"));
c.push(meta("Word count (main text)","[TODO: Brain limit 6000]"));
c.push(meta("Abstract","\u2264400 words (Brain limit)"));
c.push(meta("Display items","6 figures, 1 table (Brain limit 8)"));

c.push(h1("Abstract"));
c.push(para("Cortical hyperexcitability is one of the more reliable physiological markers in amyotrophic lateral sclerosis (ALS). It appears before symptoms and tracks how fast the disease progresses. Almost everything we know about the network signatures used to follow it, however, comes from SOD1 and FUS models. In those models a deficit in theta-gamma phase-amplitude coupling (PAC), tied to noradrenaline depletion, marks cortical hyperexcitability. In sporadic patients the same deficit is frequency-specific and confined to the dominant sensorimotor cortex. It is not known whether any of this carries over to C9orf72-mediated disease. That gap matters. C9orf72 is the commonest genetic cause of ALS and frontotemporal dementia, and it is mechanistically distinct in that it involves loss of C9orf72 function. Whether one network biomarker can serve a genetically mixed patient population depends on the answer. We recorded hippocampal (CA3) and parietal sensorimotor (S1/PtA) cortical EEG, with synchronous video, in C9orf72-knockout mice and wild-type littermates at six timepoints from 3 to 12 months. These spanned a pre-symptomatic baseline, an acute kainic-acid challenge, and the progression to end-stage. Analyses followed a pre-specified, false discovery rate-controlled plan with per-timepoint comparisons and mixed-effects trajectory modelling. The dominant finding was a biphasic trajectory of network dysfunction, clearest during REM sleep. Relative beta power was raised in knockout mice during the acute phase (4 months; REM Cohen\u2019s d = 1.27, wake d = 1.26) and lowered at end-stage (12 months; REM d = \u22121.66, wake d = \u22121.61). Per-timepoint tests in both directions supported this reversal, as did a cluster-robust mixed-effects model (interaction p = 0.048). The REM theta/delta ratio rose sharply at challenge (d = 1.97), and REM relative theta stayed elevated through 9 months (d = 1.76). Sleep architecture drifted progressively toward entering REM directly from NREM (12 months d = 3.85). Unlike SOD1 and FUS mice, the knockouts showed no cortical theta-gamma PAC deficit during REM at any timepoint, a genotype-specific divergence. A behavioural battery at 10 months showed impairment across several domains in knockout mice: grip strength (d = \u22121.23) and cued fear freezing (d = \u22121.84) were significantly reduced, with large-effect reductions in recognition memory and locomotion. The small phenotyped sample meant we could not reliably link individual network features to behaviour at the level of single animals. Taken together, the data point to REM sleep as a sensitive window on C9orf72 network dysfunction. They describe a genotype-specific, biphasic trajectory that mirrors the hyperexcitable-to-hypoexcitable shift seen in human ALS, with implications for how network biomarkers are developed and stratified."));
c.push(rich([new TextRun({text:"Keywords: ",bold:true}),new TextRun("C9orf72; amyotrophic lateral sclerosis; frontotemporal dementia; EEG; REM sleep; cortical network dysfunction; phase-amplitude coupling")]));

c.push(h1("Introduction"));
[
"Amyotrophic lateral sclerosis (ALS) is a fatal neurodegenerative disease in which upper and lower motor neurons are progressively lost; most patients die within two to five years of their first symptoms. One physiological feature recurs across both sporadic and familial forms: cortical hyperexcitability. It is present before motor symptoms appear, it correlates negatively with survival, and in rodent models it is on its own enough to set off neurodegeneration. Being able to detect and follow this network dysfunction non-invasively would help a great deal with early diagnosis, with sorting patients into meaningful subgroups, and with reading out whether a treatment is working. Those needs are particularly pressing in a disease whose clinical variability both delays diagnosis and makes trials hard to design.",
"A hexanucleotide repeat expansion in C9orf72 is the single most common genetic cause of ALS and frontotemporal dementia, accounting for a large share of familial cases and a meaningful slice of apparently sporadic ones. [TODO insert precise prevalence figures with citation.] For all that prominence, the network-level electrophysiology of C9orf72 disease has had relatively little attention. Most of our picture of ALS cortical network dysfunction comes instead from SOD1 and FUS models. Recent work in those models established a deficit in theta-gamma phase-amplitude coupling (PAC) as a traceable readout of cortical hyperexcitability. The deficit is detectable from pre-symptomatic stages, it correlates with progression rate in patients, and it is mechanistically tied to a shortage of cortical noradrenaline [ref: Scekic-Zahirovic et al. 2024]. In sporadic patients the signature is sharper still. Theta-gamma PAC is selectively reduced in the dominant (usually left) sensorimotor cortex, while alpha-gamma and beta-gamma coupling and band power are unchanged, and its diagnostic performance beats diffusion MRI [ref: Benetton et al. 2025]. The benchmark a new model has to be measured against is therefore well specified: a frequency-specific, noradrenaline-linked, dominant-hemisphere theta-gamma deficit. But these are largely gain-of-function models. C9orf72 disease is different. It pairs repeat-associated gain-of-function toxicity with loss of the C9orf72 protein itself, which affects autophagy and immune regulation. A C9orf72-knockout isolates that loss-of-function arm, so its particular contribution to network pathophysiology can be looked at on its own. Different genetic subtypes of ALS recruit partly different molecular pathways, and there is no guarantee the network phenotypes line up. Whether the SOD1/FUS coupling signature is a universal correlate of ALS cortical dysfunction or a subtype-specific one is, at present, unknown. The answer speaks directly to whether a biomarker calibrated in one genetic background will transfer to another.",
"Sleep is a particularly informative window onto cortical state. Each vigilance state imposes its own oscillatory regime, and in rodents REM sleep stands out for prominent theta and gamma activity that is exquisitely sensitive to the balance between excitation and inhibition. REM is also the state in which several neuromodulatory systems that normally keep cortical excitability in check fall to their lowest tone. Disrupted sleep architecture and altered state-specific oscillations are increasingly recognized as early signs of neurodegeneration. We reasoned that following the EEG longitudinally and state by state, rather than taking a single cross-sectional snapshot, would give the best chance of seeing how network function evolves across the C9orf72 disease course, and that REM in particular might bring latent abnormalities to the surface.",
"That is the study we report here. In C9orf72-knockout mice and wild-type littermates, we recorded EEG from hippocampal and cortical electrodes, with synchronous video, at six timepoints from 3 to 12 months: a pre-symptomatic baseline, an acute kainic-acid challenge meant to probe network vulnerability, and the slide toward end-stage. With a pre-specified, false discovery rate-controlled analysis, backed up by mixed-effects trajectory modelling and by analysis of sleep-state transitions, we set out to answer three questions. Does network function change across the disease course, and how? Are any such changes state-specific? And is the theta-gamma PAC signature seen in other ALS models present here? What we found was a biphasic trajectory of network dysfunction concentrated in REM sleep and, in contrast to the SOD1 and FUS models, no cortical theta-gamma PAC deficit. The two together mark out a genotype-specific network phenotype."
].forEach(t=>c.push(para(t)));

c.push(h1("Materials and methods"));
c.push(para("This study is reported in accordance with the ARRIVE guidelines."));
c.push(h2("Animals"));
c.push(para("All animal procedures were conducted in accordance with the Canadian Council on Animal Care and approved by the University of Toronto Animal Care Committee (UHN AUP 6436; MRAP AUP 20012840). C9orf72-knockout mice were generously provided by Dr Don Cleveland (University of California, San Diego) and Dr Clotilde Lagier-Tourenne (Harvard University) and were maintained on a C57BL/6 background (Charles River Laboratories); genotyping followed Jiang et al. (2016). Heterozygous C9orf72 mice were crossed with wild-type mice and the resulting heterozygotes intercrossed to generate wild-type (WT), heterozygous (C9-HET), and homozygous-knockout (C9-KO) littermates. Animals were housed under standard conditions (\u22645 same-sex mice per cage) on a 12-h light/12-h dark cycle (lights on 07:00) with food and water ad libitum. Sex was recorded for all animals; balanced male/female representation was achieved only in selected experiments, so sex-specific analyses were performed only where numbers permitted. For the electrophysiological study reported here, C9-HET mice were not included, because prior behavioural seizure analyses showed no significant difference between C9-HET and WT animals; to limit animal use, EEG was therefore restricted to the WT and C9-KO genotypes, which exhibited clearly distinct phenotypes. Experimenters were blinded to genotype during recording, sleep-state scoring, event detection, and analysis; genotype was unblinded only for final statistical comparison."));
c.push(h2("Animal flow and attrition"));
c.push(para("Animals were implanted and entered the longitudinal protocol at 3 months of age (wild-type n = 9, knockout n = 9). Continuous 24-hour EEG with synchronous video was then acquired at 3, 4, 6, 7, 9, and 12 months. The number of animals contributing usable recordings declined with age, as expected for an end-stage neurodegeneration model: wild-type and knockout counts were 9/9 at 3 months, 8/8 at 4 and 6 months, 8/6 at 7 months, 6/4 at 9 months, and 4/4 at 12 months. The behavioural battery at 10 months was administered to the surviving cohort (wild-type n = 9, knockout n = 9; per-subtest n = 8\u201314 depending on the measure). The full flow is shown in Supplementary Fig. S1. The per-timepoint counts reported here reflect animals with usable, video-paired recordings at each session and are a lower bound on the number contributing EEG; final enrolment and attrition figures, together with reasons for loss at each stage, are to be reconciled against the master study log before submission [TODO: confirm against enrolment log]."));
c.push(para("Of [N] animals enrolled, [N] knockout and [N] wild-type contributed usable recordings at the 3-month baseline. Cohort size decreased at later timepoints owing to [attrition causes TODO], yielding [N] per group at 12 months. Missing data arising from attrition were handled by complete-case per-timepoint analysis and by the mixed-effects model\u2019s accommodation of unbalanced repeated measures; no values were imputed. The reduction in end-stage sample size is considered explicitly in the interpretation of late-timepoint effects."));
c.push(h2("EEG and video recording"));
c.push(para("Bipolar electrode implantation followed Bin et al. (2017). At 3 months of age, C9-KO and WT mice were implanted with two pairs of polyamide-insulated twisted stainless-steel micro-electrodes (200 \u00B5m outer diameter; Plastics One). Electrodes were stereotaxically positioned in the right CA3 hippocampus (AP \u22122.5, ML +3.0, DV \u22123.0 mm from bregma) and the left contralateral parietal sensorimotor cortex (S1/PtA; AP \u22122.0, ML \u22122.0, DV \u22121.5 mm), with a reference electrode in the frontal region (AP +1.0, ML +1.0, DV \u22120.5 mm). The cortical site is parietal sensorimotor cortex and is anatomically distinct from primary motor cortex (M1); this distinction is examined in detail in a companion study of circuit-specific dissociation [ref: companion paper]. Electrodes were fixed with dental acrylic on a custom polystyrene baseplate as described (Bin et al., 2017; Liu et al., 2019, 2021)."));
c.push(para("After one week of recovery, continuous 24-h EEG\u2013video monitoring was performed with each mouse in a modified cage with food and water ad libitum. A slip-ring commutator (Digikey 1528-1152-ND) mounted atop the cage connected to the implanted electrodes via flexible cabling, permitting free movement without cable entanglement. Video was acquired at 20\u201325 frames per second (Logitech C615 webcam) under white light during the light phase and dim light during the dark phase. EEG and video were saved every 2 h; monitoring was briefly paused (10\u201330 min) for cage maintenance as needed. Recordings were obtained at six timepoints: 3 months (pre-symptomatic baseline, before kainic-acid administration), 4 months (the kainic-acid challenge day), and 6, 7, 9, and 12 months. EEG was stored in Axon Binary Format with synchronous video for behavioural annotation and movement quantification; signals were down-sampled to 500 Hz after anti-alias decimation and segmented into 4-second epochs for analysis."));
c.push(h2("Kainic-acid challenge"));
c.push(para("The kainic-acid assay followed Rizwan et al. (2019). A maximum tolerated dose of 20 mg/kg was established by structured dose-ranging in female C57BL/6 mice. At 4 months of age (one month after electrode implantation), mice received kainic acid (20 mg/kg i.p.; Alomone Labs) and EEG\u2013video was recorded for 180 min. Seizure activity was scored every 3 min over 180 min using a modified Racine scale (Racine, 1972; Rizwan et al., 2019). The kainic-acid challenge serves in this study as a standardized excitotoxic stressor probing network reactivity at the 4-month timepoint."));
c.push(para("At the 4-month timepoint, animals received kainic acid to probe network vulnerability. Recordings at this timepoint therefore capture the network response to an acute excitotoxic challenge rather than a spontaneous state, a distinction maintained throughout the interpretation."));
c.push(h2("Sleep-state classification"));
c.push(para("Each 4-second epoch was classified as wake, NREM, or REM from cortical relative band-power features computed by Welch\u2019s method, after exclusion of artefactual epochs (absolute amplitude > 500 \u00B5V or near-flat signal). Within each recording, band powers and signal variance were z-scored. Wake was assigned to epochs with high signal variance (above the 75th percentile within recording) or elevated fast-frequency activity (beta or gamma z-score > 1); REM to non-wake epochs that were theta-dominant and low-delta (delta/theta ratio below half the within-recording median, positive theta z-score, variance below the 75th percentile); and NREM to delta-dominant epochs (delta/theta above the median). Incorporating signal variance into wake detection provides a partial movement/arousal criterion that helps separate active wakefulness from REM. The approach was applied identically to all recordings and yielded biologically plausible state distributions (REM 7\u201312% of total recording time, ~20\u201329% of sleep). Because classification used EEG without concurrent electromyography, the resulting REM state was validated against synchronous video and sleep architecture (see Results and Fig. S7) and the limitation is considered in the Discussion. Epoch-level labels were retained for state-specific spectral analysis and for analysis of state-transition dynamics."));
c.push(h2("Spectral and signal features"));
c.push(para("For each epoch we computed absolute and relative band power (delta 0.5\u20134 Hz, theta 4\u20138 Hz, alpha 8\u201313 Hz, beta 13\u201330 Hz, gamma 30\u201380 Hz), the theta/delta ratio, spectral entropy, Hjorth parameters, signal variance, peak-to-peak amplitude, zero-crossing rate, and Lempel-Ziv complexity. Sleep spindles were detected and their duration quantified as an index of thalamocortical circuit integrity. The aperiodic (1/f) exponent of the power spectrum was estimated to characterize the scale-free component of cortical activity. Features were aggregated within each vigilance state to yield state-specific summaries per recording."));
c.push(h2("Phase-amplitude coupling"));
c.push(para("To test for the theta-gamma PAC signature reported in other ALS models, we computed the modulation index after the method of Tort and colleagues. Coupling was assessed between theta phase (4\u20138 Hz) and both low-gamma (30\u201380 Hz) and high-gamma (80\u2013150 Hz) amplitude, and between alpha phase (8\u201313 Hz) and the same amplitude bands, separately for each vigilance state and recording channel. Matching the published cross-model finding, the pre-specified primary test was cortical theta-high-gamma coupling during REM sleep."));
c.push(h2("Circuit dissociation"));
c.push(para("To quantify divergence between hippocampal and cortical spectral state, we computed dissociation indices comparing CA3 and S1/PtA channels, including a decorrelation index defined as one minus the Spearman correlation of the two channels\u2019 band-power profiles. Trajectories of these indices were compared between genotypes across timepoints."));
c.push(h2("Behavioural testing"));
c.push(para("A behavioural battery was administered at 10 months of age. Open-field activity was recorded for 10 min in a 100 \u00D7 100 cm arena and scored with ANY-maze (Stoelting), yielding total distance travelled, time in centre, centre/total ratio, time mobile, and mean speed. Grip strength (all four paws) was measured with a grip-strength meter (Bioseb BIO-GT3) as the peak force over three averaged trials. Novel object recognition followed Alfieri et al. (2016): after four daily habituation sessions, mice explored two identical objects (phase I, 10 min) and, 1 h later, one familiar and one novel object (phase II, 5 min); exploration was scored from video (ODLog 2), and the memory/discrimination index was computed as (novel \u2212 familiar)/(novel + familiar) exploration time. Fear conditioning used Freeze Monitor chambers (San Diego Instruments) over three days: conditioning in context A with a tone co-terminating with two 0.6 mA foot shocks (day 1), contextual testing in context A without tone (day 2), and cued testing in context B with tone (day 3); percent freezing (absence of movement except respiration, from beam breaks) indexed contextual and cued memory respectively. Rotarod was also performed (accelerating 4\u201340 rpm; mean latency to fall over the final three of seven trials). Behavioural scoring was performed blinded to genotype."));
c.push(h2("Parvalbumin immunohistochemistry"));
c.push(todo("Describe tissue collection at 12 months, sectioning, parvalbumin immunolabelling, imaging, and quantification of PV-positive interneuron density and mean fluorescence intensity in cortex and hippocampus, \u22653 sections per region per animal."));
c.push(h2("Statistical analysis"));
[
"EEG features were compared between knockout and wild-type mice using a hierarchical strategy. The primary analysis tested pre-specified spectral features at four disease-relevant timepoints (3, 4, 9, and 12 months), with 6- and 7-month timepoints reserved for secondary exploration. For each feature-by-timepoint comparison we computed Mann-Whitney U tests, Cohen\u2019s d with bias-corrected 95% bootstrap confidence intervals (2000 resamples), and applied Benjamini-Hochberg false discovery rate (FDR) correction across the 20 primary tests. Effects are reported as statistically supported when the FDR-adjusted q-value was below 0.05, and as showing effect-size evidence when the bootstrap confidence interval excluded zero.",
"Because the design involved repeated measurements of the same animals across timepoints, trajectory divergence was tested with linear mixed-effects models of the form feature ~ genotype \u00D7 time + (1 | animal), the genotype-by-time interaction quantifying differential change over time. Where the random-intercept variance was estimated near the boundary of the parameter space, we report ordinary least-squares regression with cluster-robust standard errors (clustered by animal) as a sensitivity analysis, since cluster-robust inference accounts for within-animal dependence without requiring an estimable variance component; a trajectory effect is reported as supported only when it survived this sensitivity test.",
"To distinguish whether genotype effects arose at the level of the animal or of individual recording sessions, all analyses were conducted under two unit-of-analysis definitions: a conservative primary analysis treating each animal as the experimental unit, and a sensitivity analysis treating each recording session as the unit. The animal-level analysis is reported as primary throughout; session-level results are provided as supplementary sensitivity comparisons.",
"Sleep-state transition dynamics were quantified from epoch-level state classifications as per-animal three-by-three transition probability matrices, state-specific mean dwell times, and transition rates, with group comparisons by Mann-Whitney U test and Cohen\u2019s d."
].forEach(t=>c.push(para(t)));
c.push(para("Brain\u2013behaviour and brain\u2013histology relationships were assessed at the level of individual animals. Per-animal EEG features (for example REM relative theta and beta, theta/delta ratio, and signal-complexity measures at the relevant timepoint) were correlated with behavioural scores from the 10-month battery and, where available, with parvalbumin-interneuron measures, using Spearman rank correlation. Two relationships were pre-specified: 9-month REM theta against novel object recognition, and the 3-to-12-month beta change against grip strength. Because behaviour was assessed at 10 months without concurrent EEG, pre-specified features were tested against the nearest sessions (9 and 12 months). Correlations were computed within the behaviourally phenotyped subset (n = 8\u201314 depending on measure) and corrected for multiple comparisons with the Benjamini\u2013Hochberg false discovery rate across the pre-specified set; exploratory correlations outside that set are reported uncorrected and identified as hypothesis-generating. Given the modest phenotyped sample, individual correlation coefficients are interpreted with caution and emphasis is placed on the group-level phenotype."));
c.push(h2("Data and code availability"));
c.push(rich([new TextRun("Analysis code is available at https://github.com/BelayTG/eeg-video-analysis-c9orf72. ")]));
c.push(todo("Data availability statement; OSF repository and embargo status."));

c.push(h1("Results"));
const R=[
["A longitudinal, state-resolved EEG dataset across the C9orf72 disease course","We recorded two-channel EEG with synchronous video from C9orf72-knockout mice and wild-type littermates at six timepoints, spanning pre-symptomatic, acute-challenge, and progressive disease stages (Fig. 1). Epoch-level vigilance-state classification yielded biologically plausible distributions, with REM sleep at 7\u201312% of total recording time (~20\u201329% of sleep). This allowed state-resolved spectral analysis throughout the disease course and supported both per-timepoint comparison and the modelling of within-animal trajectories."],
["A biphasic reversal of beta-band network activity is the central longitudinal finding","The defining feature of the trajectory was a reversal in the direction of the between-genotype difference in beta-band power (Fig. 2). During the acute challenge phase at 4 months, relative beta power was elevated in knockout mice in both REM (wild-type 0.108, knockout 0.159; Cohen\u2019s d = 1.27; FDR q = 0.047) and wakefulness (wild-type 0.091, knockout 0.166; d = 1.26; FDR q = 0.047). By end-stage at 12 months the difference had reversed, with relative beta reduced in knockout mice in both REM (wild-type 0.159, knockout 0.135; d = \u22121.66) and wakefulness (wild-type 0.152, knockout 0.122; d = \u22121.61), both reaching FDR significance in the session-level analysis. The reversal was supported at the trajectory level: the genotype-by-time interaction for REM relative beta was significant under cluster-robust inference (interaction p = 0.048), indicating that the knockout and wild-type beta trajectories diverged over time rather than differing only at isolated timepoints. Elevated beta during the acute phase gave way to reduced beta at end-stage. This biphasic course is compatible with the hyperexcitable-to-hypoexcitable transition described in human ALS, seen here as a longitudinal change within the same animals."],
["Acute REM dysregulation at the challenge timepoint","At the 4-month kainic-acid challenge, knockout mice showed broad dysregulation of REM oscillations (Fig. 3; Table 1). The REM theta/delta ratio was markedly elevated (wild-type 0.78, knockout 1.42; d = 1.97; FDR q = 0.047), the largest single effect in the dataset, accompanied by elevated REM relative theta (d = 1.50) and relative alpha (d = 1.38), with confidence intervals excluding zero. The acute response to excitotoxic challenge thus appeared as a shift of the REM spectral profile toward faster, theta-dominant activity. Because the REM theta/delta ratio did not show a monotonic genotype-by-time divergence under cluster-robust inference (robust interaction p = 0.34), we interpret this as a timepoint-specific acute effect rather than a progressive trajectory. The joint per-timepoint and trajectory analyses make this distinction explicit."],
["Persistent theta dominance at the progressive stage","At 9 months, REM relative theta remained elevated in knockout mice (wild-type 0.35, knockout 0.40; d = 1.76; FDR q = 0.023, session-level), accompanied by a reduced REM zero-crossing rate (d = \u22120.99), indicating a slower, more regular REM EEG. The theta dominance that emerged acutely at challenge thus persisted into the progressive stage, consistent with a sustained alteration of REM network state."],
["Progressive destabilization of sleep-state architecture","Beyond spectral content, the dynamics of vigilance-state transitions were altered in knockout mice (Fig. 4). Knockout animals showed an increased probability of transitioning from NREM into REM sleep, an effect that intensified with age and was large at end-stage (12 months: wild-type 0.21, knockout 0.26; d = 3.85), accompanied by prolonged REM dwell time at 9 months (d = 1.66). Because REM was the state in which the spectral abnormalities were most pronounced, this transition bias indicates that the architecture of sleep itself becomes progressively skewed toward the most affected state. End-stage transition statistics rest on a small sample (n = 4 per group) and are interpreted with corresponding caution."],
["No cortical theta-gamma PAC deficit: a genotype-specific divergence from SOD1 and FUS models","Theta-gamma PAC is an established cortical hyperexcitability readout in SOD1 and FUS models, and in sporadic ALS patients it is a frequency-specific, dominant-hemisphere deficit confined to theta-gamma coupling. We therefore tested directly for this signature in C9orf72-knockout mice, matching the published methodology in coupling bands, vigilance state, recording site, and pre-symptomatic timepoint (Fig. 5). Our cortical electrode sat over left (dominant-side) sensorimotor cortex, the region in which the human deficit is maximal, so a null result here reflects absence of the signature at the site where it should be most detectable rather than sampling of an unaffected region. Contrary to the pattern in those models, cortical theta-high-gamma PAC during REM did not differ between genotypes at any timepoint (3 months d = 0.25; 4 months d = 0.02; 12 months d = 0.02; all non-significant), and where differences trended they did not favour reduced coupling in knockout mice. The absence held across the full coupling matrix tested (theta- and alpha-phase against low- and high-gamma amplitude). The only coupling effects with confidence intervals excluding zero were hippocampal, during NREM, at later timepoints (9-month CA3 alpha-low-gamma d = \u22121.51; 12-month CA3 alpha-high-gamma d = \u22121.15). This is a different channel, state, and frequency combination from the cortical theta-gamma signature reported in humans and other models. C9orf72-knockout mice therefore do not reproduce the cortical theta-gamma PAC deficit that characterizes SOD1 and FUS disease, indicating that this coupling signature is not a universal feature across ALS genetic subtypes. Two further checks support this null. First, across the full cortical-REM coupling matrix (four phase bands by two gamma amplitude bands by three principal timepoints; 24 comparisons), no cell reached FDR significance (Supplementary Fig. S2). The absence is therefore general across the coupling space rather than specific to a single under-powered test. Second, because the modulation index can be biased by amplitude-band power, we examined gamma-band power directly. At the timepoints where cortical PAC was null, gamma power either did not differ between genotypes or, at the 4-month challenge, was modestly reduced in knockout mice (d = \u22120.45), a direction that would tend to depress rather than inflate a coupling estimate. That coupling held up even as gamma amplitude fell tells us the null is conservative rather than a power artifact (Supplementary Fig. S3)."],
["Latent thalamocortical and circuit-level signatures","At the 3-month pre-symptomatic baseline, sleep spindle duration was reduced in knockout mice (wild-type 1.02 s, knockout 0.94 s; d = \u22121.34; confidence interval excluding zero), a latent thalamocortical signature detectable before overt disease. Spindle rate was uninformative; duration was not, which underscores the value of event-level over count-level metrics. At 7 months, CA3-S1/PtA delta coherence was reduced in knockout mice (d = \u22121.28; confidence interval excluding zero). Circuit dissociation between the hippocampal and sensorimotor cortical channels also rose progressively with age in knockout but not wild-type animals (knockout decorrelation trajectory \u03C1 = 0.43, p = 0.007; wild-type \u03C1 = 0.06, not significant). This points to a developing functional disconnection between the two structures; its spatial layout is characterized in a companion study [ref: companion paper]. There was also a prospective relationship: the aperiodic (1/f) exponent at the 3-month baseline predicted Lempel-Ziv complexity at 12 months (Spearman \u03C1 = 0.929; FDR q = 0.034), suggesting that features of the pre-symptomatic cortex foreshadow the eventual network phenotype."]
];
R.forEach(([t,b])=>{c.push(h2(t));c.push(para(b));});
c.push(h2("Headline features classify genotype with cross-validated accuracy"));
c.push(para("We then asked whether the network features distinguish genotype at the level of individual animals. That is the property separating a biomarker from a group difference. We evaluated classification performance with leave-one-out and repeated stratified k-fold cross-validation, reporting out-of-sample area under the receiver operating characteristic curve (AUC) and a label-permutation null (5000 permutations). Three features classified genotype above chance under cross-validation and survived permutation testing. These were REM relative beta at 4 months (cross-validated AUC = 0.81; permutation p = 0.004), REM theta/delta ratio at 4 months (AUC = 0.83; p = 0.007), and the pre-symptomatic sleep-spindle duration at 3 months (AUC = 0.72; p = 0.017). For context, the theta-gamma PAC biomarker reported in sporadic ALS patients achieved an AUC of 0.858 against healthy controls [ref: Benetton et al. 2025]; the acute REM features here reach comparable single-feature discrimination between genotypes, and the pre-symptomatic spindle measure provides a baseline classifier detectable before overt disease. Cross-validation made two limitations explicit. First, the end-stage (12-month) beta reduction, although directionally consistent, did not reach a defensible out-of-sample classification (AUC = 0.69; permutation p = 0.11; n = 8), so we report it as a trajectory rather than a standalone classifier. Second, the 3-month aperiodic exponent, while a strong longitudinal predictor of later complexity, did not classify genotype out-of-sample, and we interpret it only in its predictive role."));
c.push(h2("Robustness of REM findings to classification thresholds"));
c.push(para("Because REM was identified from relative band-power criteria rather than concurrent electromyography, we tested whether the principal REM findings depended on the specific thresholds chosen. Each headline REM feature was recomputed under a grid of 81 threshold combinations spanning a range of theta, delta, and variance percentile cutoffs. The two acute findings were stable across the entire grid. 4-month REM relative beta remained elevated in knockout mice at every threshold combination (Cohen\u2019s d range +1.32 to +1.58; FDR-significant in 100% of grid points), as did the 4-month REM theta/delta ratio (d range +1.19 to +1.41; significant in 100% of grid points). The end-stage beta reduction was directionally stable (d range \u22121.72 to \u22121.41; same sign in 100% of grid points) though, consistent with its smaller sample, not individually significant across the grid. The principal REM effects are therefore not artifacts of any single classification cutoff."));
c.push(h2("Synchronous video confirms that REM-classified epochs are behaviourally quiescent"));
c.push(para("Because vigilance states were defined from EEG without electromyography, we used the synchronous video to test the principal concern for EMG-free staging: that theta-rich, low-delta epochs labelled REM might instead be active, exploratory wakefulness. Per-epoch movement was quantified as frame-to-frame video motion energy and aligned to the EEG epochs. Three convergent results support the REM classification. First, across the full cohort REM occupied a physiological fraction of recording time (7.0\u201310.3% of total epochs; ~21\u201329% of sleep) at every timepoint in both genotypes. That is consistent with normal mouse REM and argues against substantial active-wake inflation. Second, of the 20,436 epochs the classifier labelled REM, 91.6% were behaviourally immobile, the highest immobile fraction of any state (REM 92%, NREM 90%, wake 90% immobile). Average wake motion is dominated by quiet rest, so the diagnostic contrast is with active wakefulness specifically. When wake was split into quiet and active (the upper movement quartile), REM movement fell far below active wake (Cohen\u2019s d = \u22121.28, Mann-Whitney p < 10\u207B\u2078). That is the comparison that bears on the active-wake confound. REM itself sat marginally below quiet wake and NREM, the three sleep and quiet states being similarly immobile. Third, the staging reproduced canonical sleep architecture. REM was rarely entered directly from wake (wake\u2192REM transition probability 0.07), it showed self-maintenance, and its bout durations were physiological. Hippocampal CA3 theta was greatest during REM, with a ~6.5 Hz peak characteristic of rodent REM theta (CA3 theta/delta REM vs wake Cohen\u2019s d = +0.36). On every one of these measures the EEG-defined REM state behaves like real REM. It is immobile, theta-dominant, hippocampally appropriate, and entered through the expected route, not like misclassified active wakefulness. The one caveat, that video immobility stands in for muscle atonia rather than measuring it directly, is taken up in the Discussion."));
c.push(para("To test whether the cortical network retained its normal relationship to behaviour, we used the synchronous video to quantify corticomotor predictive coupling, the degree to which cortical beta-band activity in one epoch predicted movement in the next, at every timepoint. Because each animal contributed many video epochs (median 10 recordings per animal, range 1\u201345), analyses were collapsed to a single coupling value per animal per timepoint and genotypes compared with the animal as the unit of replication. At this level, predictive coupling did not differ between knockout and wild-type mice at any timepoint (3m d = 0.03; 4m d = 0.39; 6m d = \u22120.87; 7m d = \u22120.38; 9m d = 0.58; 12m d = 1.20; all p > 0.10, none surviving false discovery rate correction). The preservation of corticomotor coupling, in the same animals and timepoints where REM network dynamics were markedly abnormal, indicates that the C9orf72 phenotype reported here is specific to sleep-state network organization. It does not reflect a global breakdown of the relationship between cortical activity and behaviour. An epoch-level analysis, which treats each video frame-pair as independent, does yield an apparently significant end-stage difference. This is an artifact of pseudoreplication: thousands of within-animal epochs inflate the effective sample size. It does not hold once the animal is the unit of analysis, which underscores the importance of animal-level inference for this measure."));
c.push(h2("A multi-domain behavioural phenotype at the progressive stage"));
c.push(para("To establish whether the network trajectory is accompanied by functional impairment, a behavioural battery was administered to a subset of the cohort at 10 months of age, between the 9- and 12-month EEG sessions, comprising novel object recognition, open-field exploration, cued and contextual fear conditioning, and grip strength. Knockout mice showed a coherent, multi-domain impairment spanning motor, cognitive, and associative-memory measures. Grip strength was reduced in knockout mice (wild-type 260.5 vs knockout 231.1 g; Cohen\u2019s d = \u22121.23, p = 0.045), and cued freezing during fear conditioning was likewise reduced (39.8% vs 26.1%; d = \u22121.84, p = 0.012). Three further measures showed large effect sizes in the same impaired direction without reaching significance at the available sample size: novel object discrimination (index 0.57 vs 0.13; d = \u22121.22, p = 0.059), open-field distance travelled (28.3 vs 18.8 m; d = \u22121.53, p = 0.065), and locomotor velocity (4.7 vs 3.1 cm/s; d = \u22121.54, p = 0.065). Contextual and baseline freezing did not differ significantly. The convergence of a motor readout (grip, locomotion), a recognition-memory readout (novel object discrimination), and an associative-memory readout (cued freezing) indicates that loss of C9orf72 function produces impairment across multiple behavioural domains rather than a single isolated deficit. The reduction in cued freezing is telling: it occurred despite reduced general locomotion, not because of it, since hypoactivity would be expected to increase freezing rather than decrease it."));
c.push(para("We then tested the pre-specified hypotheses linking individual EEG features to behavioural performance: that 9-month REM theta would predict recognition memory, and that the late-stage beta reduction would track grip-strength decline. Within the behaviourally phenotyped subset (n = 8\u201314 depending on measure and timepoint), neither pre-specified brain\u2013behaviour correlation survived false discovery rate correction. The two specific predictions were not individually significant either (9-month REM theta vs novel object discrimination, Spearman \u03c1 = \u22120.37, p = 0.29; 9-month REM beta vs grip, \u03c1 = 0.35, p = 0.33). Because behaviour was assessed at 10 months, no EEG was recorded concurrently. The pre-specified features were therefore tested against the nearest sessions, at 9 months (one month before testing) and 12 months (two months after), and the grip-strength prediction was further tested against the 3-to-12-month beta trajectory. None of these was supported. Exploratory, uncorrected analysis turned up scattered associations between progressive-stage EEG measures and behaviour, for example 9-month REM signal-complexity measures with grip strength (Lempel\u2013Ziv complexity \u03c1 = \u22120.79, p = 0.006; spectral entropy \u03c1 = 0.71, p = 0.022). But at these sample sizes individual coefficients are unstable, they were not pre-registered, and none survive correction; we report them only as hypothesis-generating. The behavioural data therefore establish that the C9orf72-knockout model is functionally impaired across motor and cognitive domains at the progressive stage. The modest behavioural sample, however, precludes robust individual-level coupling between specific network features and behavioural scores. That would require a substantially larger phenotyped cohort, and we identify it as a priority for prospective work."));
c.push(h2("Parvalbumin interneuron correlates"));
c.push(ph("Parvalbumin-positive interneuron density and intensity in cortex and hippocampus at 12 months are being quantified. Pre-specified hypotheses: animals with the lowest spindle duration and beta power show the greatest parvalbumin loss, and 3-month EEG features predict 12-month parvalbumin density, which would provide a cellular substrate (interneuron integrity) for the network trajectory. Tissue processing in progress."));

c.push(h1("Discussion"));
[
"In a longitudinal, state-resolved electrophysiological study spanning the C9orf72-knockout disease course from a pre-symptomatic baseline to end-stage, we identify a biphasic trajectory of network dysfunction expressed most clearly during REM sleep, and we show that this phenotype diverges from that of the better-studied SOD1 and FUS models. The central longitudinal finding is a reversal in beta-band activity, elevated in knockout mice during the acute challenge phase and reduced at end-stage, supported by per-timepoint testing in both directions and by cluster-robust trajectory modelling. This biphasic pattern is compatible with the hyperexcitable-to-hypoexcitable transition described in human ALS, in which early cortical hyperexcitability gives way to reduced cortical output as the disease advances. We are careful to frame these spectral changes as network dysfunction rather than as direct measures of neuronal excitability, which would require cellular or stimulation-based assays beyond the present EEG measures; the parallel to the human excitability transition is therefore offered as a compatibility, not an identity.",
"The result with the widest implications is a comparative one. We tested directly, using matched coupling bands, vigilance state, recording site, and pre-symptomatic timepoint, for the cortical theta-gamma PAC deficit that characterizes SOD1 and FUS models, and found no such deficit in C9orf72-knockout mice at any stage. This dissociation is informative rather than merely negative, and three features of the human and cross-model literature make it harder to dismiss as a null of convenience. First, the human deficit is frequency-specific: in sporadic ALS patients, theta-gamma coupling is selectively reduced while alpha-gamma and beta-gamma coupling and band power are preserved [ref: Benetton et al. 2025], so our matched theta-gamma test addressed precisely the coupling that is affected in patients, not a diffuse coupling measure. Second, the human deficit is maximal in the dominant sensorimotor cortex, which is the region our left-sided cortical electrode sampled; the null therefore arises at the site of greatest expected sensitivity rather than from sampling an unaffected area. Third, the human PAC deficit has diagnostic performance exceeding that of diffusion MRI [ref: Benetton et al. 2025], indicating a robust, readily detectable effect in patients. Its absence in the knockout is thus unlikely to reflect insufficient sensitivity of the measure. One difference in state should be stated plainly. The human PAC findings come from resting wakefulness with eyes closed, whereas our strongest mouse measures are in REM sleep. We therefore do not claim to have tested the human deficit in its own state. What we show is that the matched cortical theta-gamma coupling is absent in the knockout across wake and REM alike. SOD1 and FUS are predominantly gain-of-function models with aggressive cortical phenotypes, in which the coupling deficit has been linked to a deficiency of cortical noradrenaline; the C9orf72-knockout model isolates the loss-of-function component of repeat-expansion disease, affecting autophagy and immune regulation. That the coupling signature is absent in this context suggests that the noradrenaline-linked PAC deficit is engaged specifically by gain-of-function ALS mechanisms and is not a universal correlate of ALS cortical dysfunction. For biomarker development this carries a concrete implication: a network readout calibrated on SOD1 or FUS pathophysiology may not transfer to the substantial fraction of patients whose disease is driven by C9orf72. The phenotype we describe (REM theta dominance and biphasic beta-band change, in the absence of a cortical PAC deficit) and the SOD1/FUS phenotype thus form a double dissociation, each model expressing network abnormalities the other lacks. Given the role of genetic heterogeneity in the failure of ALS therapeutic trials, such subtype specificity in candidate biomarkers warrants attention.",
"It is striking how much of the signal sat in REM sleep. The largest acute effect, the most persistent progressive effect, and the most pronounced sleep-architecture abnormality all involved REM. REM is a state of prominent theta and gamma activity that depends sensitively on excitation-inhibition balance and in which several neuromodulatory systems that constrain cortical excitability are at their lowest tone. A network carrying a latent functional bias may therefore express that bias most readily during REM, which would account for the concentration of our findings in this state and identifies REM as a sentinel window for the detection of C9orf72 network dysfunction. The progressively increasing bias toward entering and remaining in REM compounds this, since the architecture of sleep itself becomes increasingly skewed toward the most affected state as the disease advances.",
"A few findings hint at a thalamocortical, circuit-level substrate. Reduced sleep-spindle duration at the pre-symptomatic baseline, with no change in spindle rate, points to an early alteration of thalamocortical spindle generation. The reduced CA3-S1/PtA delta coherence and the progressively increasing hippocampal-sensorimotor decorrelation in knockout animals indicate a developing functional disconnection between the structures. And the prospective link between the pre-symptomatic aperiodic exponent and end-stage complexity suggests that the baseline cortex foreshadows the eventual phenotype."
].forEach(t=>c.push(para(t)));
c.push(para("The behavioural battery confirms that this network trajectory is accompanied by functional impairment across motor and cognitive domains, with significant grip-strength and cued-freezing deficits; however, the modest phenotyped sample did not support robust individual-level correlations between specific network features and behavioural scores, and the pre-specified brain-behaviour predictions did not survive correction."));
c.push(todo("When available, the parvalbumin histology will allow these network signatures to be related directly to interneuron integrity, providing a candidate cellular substrate for the trajectory."));
[
"This study has limitations. The end-stage timepoints involved small samples; although the effects observed there were large, they are interpreted with caution, and the 12-month state-transition result in particular rests on few animals; the within-animal longitudinal design and the mixed-effects modelling mitigate but do not eliminate this concern. Sleep-state classification used relative band-power criteria rather than concurrent electromyography; although synchronous video confirmed that REM-classified epochs were behaviourally quiescent, occurred at physiological frequency, arose with appropriate sleep architecture, and carried the expected hippocampal theta signature, video immobility is a surrogate for rather than a direct measurement of muscle atonia, and the staging lacks the full specificity of polysomnography. The kainic-acid challenge at 4 months provides a controlled probe of network vulnerability but means the acute timepoint reflects a perturbed rather than a spontaneous state. Finally, the present account is primarily of the network trajectory and its behavioural correlates; while the behavioural battery establishes multi-domain functional impairment, the small phenotyped sample limits individual-level brain-behaviour inference, and the histological data that would anchor the trajectory to a cellular substrate are still being integrated and are required for the full mechanistic interpretation.",
"Within these bounds, the study establishes that C9orf72-knockout mice exhibit a distinctive, genotype-specific, biphasic trajectory of network dysfunction, expressed most clearly during REM sleep and detectable from a pre-symptomatic baseline, and that this phenotype diverges from the canonical SOD1/FUS coupling signature. By resolving the trajectory across six timepoints and three vigilance states, and by testing directly for cross-model signatures, the work characterizes C9orf72 network dysfunction in its own right and clarifies how it differs from the better-studied ALS genetic subtypes, a distinction with direct consequences for the design of network-based biomarkers in a genetically heterogeneous disease."
].forEach(t=>c.push(para(t)));

c.push(h1("Acknowledgements"));c.push(todo("Acknowledgements text."));
c.push(h1("Funding"));c.push(todo("Funding sources and grant numbers."));
c.push(h1("Competing interests"));c.push(para("The authors declare no competing interests. [TODO confirm.]"));
c.push(h1("Author contributions"));c.push(todo("Per ICMJE/CRediT."));
c.push(h1("References"));c.push(todo("Compile in Oxford/Brain Harvard style. Key citations: cortical hyperexcitability in ALS (Vucic, Kiernan); corticofugal hypothesis; C9orf72 epidemiology and biology; Scekic-Zahirovic et al. 2024 (Sci Transl Med); Tort et al. modulation index; REM theta-gamma coupling in rodents; sleep disruption in neurodegeneration; PV interneurons and cortical excitability in ALS; Gebregergis et al. 2025. Companion paper (same cohort, spatial circuit-dissociation analysis): Gebregergis, Teklu, Yhdego, \u2018Circuit-specific EEG dissociation in ALS\u2019 [in preparation/under review]; confirm consistent S1/PtA coordinates across both papers."));

c.push(h1("Table 1. Pre-specified primary analysis (animal-level)"));
c.push(table1);
c.push(rich([new TextRun({text:"Group means, Cohen\u2019s d with 95% bootstrap confidence intervals, raw and FDR-adjusted p-values. Asterisk denotes FDR q < 0.05.",italics:true,size:18})]));

c.push(h1("Figures and figure legends"));

// Figure 1 — study design
c.push(figure("figure_1_study_design.png", 460));
c.push(rich([new TextRun({text:"Figure 1. Experimental design and recording configuration. ",bold:true}),new TextRun("(A) Recording timeline across six EEG timepoints (3, 4, 6, 7, 9, 12 months) spanning a pre-symptomatic baseline, the kainic-acid challenge at 4 months, and progression to end-stage; the behavioural battery was administered at 10 months (green marker), between the 9- and 12-month EEG sessions. (B) Two-channel electrode montage (dorsal view): a hippocampal CA3 depth electrode (AP \u22122.5, ML +3.0, DV \u22123.0 mm), a left parietal sensorimotor cortical surface electrode (S1/PtA; AP \u22122.0, ML \u22122.0 mm), and a frontal reference (AP +1.0, ML +1.0 mm). (C) Recording configuration: synchronous two-channel EEG (down-sampled to 500 Hz) and video, segmented into 4-second epochs and scored as wake, NREM, or REM for state-resolved spectral, coupling, and complexity analysis. (D) Animals contributing usable synchronous recordings at each timepoint, by genotype; numbers above bars indicate animals contributing recordings. [TODO: confirm per-timepoint and total enrolment numbers against the full study log.]")]));

c.push(figure("prespecified_beta_signflip.png", 450));
c.push(rich([new TextRun({text:"Figure 2. Biphasic reversal of beta-band network activity (central finding). ",bold:true}),new TextRun("(A) Trajectories of relative beta power across timepoints, showing elevation in knockout mice at the 4-month challenge and reduction at 12 months (left), with the corresponding genotype effect-size (Cohen\u2019s d, knockout \u2212 wild-type) trajectory and bootstrap confidence intervals (right). (B, below) Mixed-effects genotype \u00D7 time trajectories for the headline REM and wake features with interaction p-values (raw and FDR-adjusted): REM relative beta, REM relative theta, and wake relative beta diverge significantly between genotypes over the disease course, whereas the theta/delta ratio and spindle duration do not survive interaction testing. The sign reversal is supported by per-timepoint testing and by the cluster-robust mixed-effects interaction.")]));
c.push(figure("mixed_effects_trajectories.png", 460));

c.push(figure("prespecified_rem_td_ratio.png", 450));
c.push(rich([new TextRun({text:"Figure 3. Acute REM dysregulation at the kainic-acid challenge. ",bold:true}),new TextRun("REM theta/delta ratio across timepoints (left) and genotype effect sizes with 95% confidence intervals at the primary timepoints (right); the ratio is elevated in knockout mice at the 4-month challenge (FDR-significant) and the primary timepoints are marked.")]));

c.push(figure("state_transition_heatmap.png", 460));
c.push(rich([new TextRun({text:"Figure 4. Progressive destabilization of sleep-state architecture. ",bold:true}),new TextRun("Vigilance-state transition-probability matrices (probability of moving from each row state to each column state) for wild-type (top) and knockout (bottom) mice at 3, 4, and 12 months, highlighting the genotype difference in REM-state self-maintenance and entry by end-stage.")]));

c.push(figure("pac_scekic_replication_summary.png", 460));
c.push(rich([new TextRun({text:"Figure 5. Absence of the cortical theta-gamma PAC deficit reported in SOD1 and FUS models. ",bold:true}),new TextRun("Theta-high-gamma modulation index across timepoints for knockout and wild-type mice in both channels (CA3, S1/PtA) and all vigilance states; the boxed cortical REM panel is the pre-specified Scekic-Zahirovic replication test, which shows no genotype difference at any timepoint.")]));

c.push(figure("dsi4_wt_ko_trajectory.png", 450));
c.push(rich([new TextRun({text:"Figure 6. Circuit dissociation between hippocampus and cortex. ",bold:true}),new TextRun("CA3\u2013S1/PtA decorrelation (1 \u2212 Spearman \u03c1) across timepoints; knockout mice show progressively increasing hippocampal-cortical decorrelation (\u03c1 = 0.43, p = 0.007) whereas the wild-type trajectory is flat, indicating a developing functional disconnection.")]));

const SUPP_START = c.length;   // boundary: everything from here is supplementary
c.push(h1("Supplementary Materials"));
c.push(para("Supplementary Methods. Expanded description of the sleep-state classification thresholds and the threshold-grid sensitivity procedure; the Tort modulation-index computation (phase and amplitude band definitions, bin count, surrogate normalization); the bias-corrected bootstrap confidence-interval procedure; the mixed-effects model specification and the cluster-robust sensitivity analysis; and the cross-validation and label-permutation procedures used for classification analysis."));
const SUPP=[
["Table S1. Session-level sensitivity analysis (Scenario B).","Full feature-by-timepoint comparisons treating each recording session as the unit of analysis, with group means, Cohen\u2019s d and 95% confidence intervals, and raw and FDR-adjusted p-values."],
["Table S2. Mixed-effects models.","Complete genotype \u00D7 time interaction results for all tested features, reporting the mixed-model p-value, the cluster-robust (by animal) p-value, the random-effect variance estimate, and the reported value (robust where the random-effect variance approached the boundary)."],
["Table S3. Sleep-state transition statistics.","Full transition-probability, dwell-time, and transition-rate comparisons between genotypes at every timepoint, with effect sizes and FDR-adjusted p-values."],
["Table S4. Secondary timepoint analyses (6 and 7 months).","Exploratory feature comparisons at the timepoints not included in the pre-specified primary analysis."],
["Table S5. Cross-validated classification performance.","For each headline feature: in-sample AUC, leave-one-out cross-validated AUC, repeated stratified k-fold AUC (mean \u00B1 SD), and label-permutation p-value."],
["Table S6. Staging-threshold sensitivity grid.","Genotype effect size and significance for each headline REM feature across all 81 threshold combinations of the band-power classifier."]
];
SUPP.forEach(([t,b])=>c.push(rich([new TextRun({text:t+" ",bold:true}),new TextRun(b)])));

// ===== Actual supplementary tables =====
c.push(h1("Supplementary Tables"));

c.push(tcap("Table S1. Session-level sensitivity analysis (Scenario B). [To be inserted from results CSV.]"));
c.push(ph("Awaiting the session-level results CSV (feature \u00D7 timepoint, treating each recording session as the unit) to populate this table with exact group means, Cohen\u2019s d [95% CI], and raw/FDR p-values."));

c.push(tcap("Table S2. Mixed-effects genotype \u00D7 time interaction (all tested features)."));
c.push(makeTable(
  ["Feature","Interaction p","FDR q","Divergence"],
  [
    ["REM relative beta","0.0003","0.002","Yes (***)"],
    ["Wake relative beta","0.0008","0.002","Yes (***)"],
    ["REM relative theta","0.0036","0.007","Yes (**)"],
    ["REM theta/delta ratio","0.344","0.514","No"],
    ["Sleep spindle duration","0.428","0.514","No"],
    ["NREM relative theta","0.886","0.886","No"]
  ],
  [3400,1800,1500,2000]
));
c.push(para("Linear mixed-effects models with genotype, age, and their interaction as fixed effects and a by-animal random intercept; p-values are the genotype \u00D7 time interaction, reported under cluster-robust (by-animal) inference where the random-effect variance approached the boundary. FDR correction is across the features listed. A significant interaction indicates that the knockout and wild-type trajectories diverge over the disease course."));

c.push(tcap("Table S3. Sleep-state transition probabilities by genotype and timepoint."));
c.push(makeTable(
  ["Genotype","Age","From state","→ Wake","→ NREM","→ REM"],
  [
    ["WT","3m","Wake","0.59","0.23","0.19"],
    ["WT","3m","NREM","0.29","0.46","0.25"],
    ["WT","3m","REM","0.26","0.26","0.48"],
    ["WT","4m","Wake","0.58","0.22","0.20"],
    ["WT","4m","NREM","0.30","0.42","0.28"],
    ["WT","4m","REM","0.28","0.27","0.45"],
    ["WT","12m","Wake","0.61","0.23","0.16"],
    ["WT","12m","NREM","0.32","0.47","0.21"],
    ["WT","12m","REM","0.32","0.27","0.41"],
    ["KO","3m","Wake","0.58","0.22","0.20"],
    ["KO","3m","NREM","0.29","0.42","0.29"],
    ["KO","3m","REM","0.24","0.27","0.49"],
    ["KO","4m","Wake","0.63","0.20","0.17"],
    ["KO","4m","NREM","0.26","0.50","0.24"],
    ["KO","4m","REM","0.26","0.27","0.47"],
    ["KO","12m","Wake","0.58","0.23","0.19"],
    ["KO","12m","NREM","0.30","0.44","0.26"],
    ["KO","12m","REM","0.28","0.30","0.42"]
  ],
  [1400,1100,1700,1500,1500,1500]
));
c.push(para("Probability of transitioning from each row (current) state to each column (next) state, by genotype at 3, 4, and 12 months (rows sum to 1). The end-stage increase in the knockout NREM\u2192REM probability and REM\u2192NREM probability, with reduced REM self-maintenance, corresponds to the destabilization of sleep-state architecture described in the Results; full dwell-time and transition-rate comparisons with effect sizes and FDR-adjusted p-values are provided in the source results file."));

c.push(tcap("Table S4. Secondary timepoint analyses (6 and 7 months). [To be inserted from results CSV.]"));
c.push(ph("Awaiting the secondary-timepoint results CSV (6- and 7-month feature comparisons) to populate exact values."));

c.push(tcap("Table S5. Cross-validated classification performance."));
c.push(makeTable(
  ["Feature (n)","In-sample AUC","LOO-CV AUC","k-fold AUC","Permutation p"],
  [
    ["4m REM relative beta (n=16)","0.92","0.81","0.93","0.004"],
    ["4m REM theta/delta (n=16)","0.89","0.83","0.90","0.007"],
    ["12m REM relative beta (n=8)","0.88","0.69","0.85","0.109"],
    ["3m spindle duration (n=18)","0.83","0.72","0.81","0.017"],
    ["3m aperiodic exponent (n=18)","0.56","0.00","0.22","0.721"]
  ],
  [3400,1800,1600,1500,1700]
));
c.push(para("In-sample, leave-one-out cross-validated, and repeated stratified k-fold AUCs, with label-permutation p-values, for each headline feature. Out-of-sample (LOO-CV) AUC is the honest performance estimate; in-sample AUC is optimistic. The two acute REM features (4-month relative beta and theta/delta) and 3-month spindle duration classify genotype above chance under permutation testing, whereas the end-stage (12-month) beta reversal and the 3-month aperiodic exponent do not survive cross-validation at the available sample size and are interpreted as trajectory and predictive features respectively rather than standalone classifiers."));

c.push(tcap("Table S6. Staging-threshold sensitivity grid (summary)."));
c.push(makeTable(
  ["Feature","d (min)","d (max)","Sign stable","FDR-significant"],
  [
    ["4m REM relative beta","+1.37","+1.52","Yes","100% of grid"],
    ["4m REM theta/delta","+1.23","+1.39","Yes","100% of grid"],
    ["12m REM relative beta","−1.68","−1.47","Yes","Directional"]
  ],
  [3000,1300,1300,1500,2100]
));
c.push(para("Genotype effect size (Cohen\u2019s d, knockout \u2212 wild-type) for each headline REM feature across the 9-point grid of theta and delta percentile thresholds (40/50/60 each). The two acute effects remain positive and FDR-significant at every grid point; the end-stage beta reduction is directionally stable (negative at every grid point) though, consistent with its smaller sample, not individually significant across the grid. Full per-cell values for all 81 threshold combinations are in the source results file."));

c.push(tcap("Table S7. Validation of EEG-defined REM against synchronous video."));
c.push(makeTable(
  ["Validation metric","Value","Expected / interpretation"],
  [
    ["REM, % of total epochs","7.0\u201310.3%","physiological mouse REM (~5\u201310%)"],
    ["REM, % of sleep","~21\u201329%","physiological"],
    ["REM epochs immobile (video)","91.6%","highest of any state \u2192 not active wake"],
    ["NREM / Wake immobile","90% / 90%","REM the most immobile state"],
    ["REM vs ACTIVE wake motion","d = \u22121.28, p < 10\u207B\u2078","the objection-relevant contrast"],
    ["Wake\u2192REM transition prob.","0.07","low; REM rarely entered from wake"],
    ["REM self-maintenance prob.","0.24","physiological REM persistence"],
    ["CA3 theta peak (REM)","~6.3 Hz","canonical rodent REM theta"],
    ["CA3 theta/delta, REM vs wake","d = +0.38","hippocampal theta greatest in REM"]
  ],
  [3100,2100,3000]
));
c.push(para("Per-epoch video motion energy and hippocampal signatures for the validation subset (knockout and wild-type at 3, 9, and 12 months). REM epochs classified from EEG were behaviourally immobile at physiological frequency, were rarely entered from wakefulness, and carried canonical hippocampal theta, indicating that the EEG-defined REM state is not misclassified active wakefulness. Because mean wake motion is diluted by quiet rest, the diagnostic contrast is with active (high-movement) wake (Fig. S7); n = 20,436 REM epochs across the full cohort."));

c.push(figure("figure_S1_animal_flow.png", 380));
c.push(rich([new TextRun({text:"Figure S1. Animal flow through the longitudinal study. ",bold:true}),new TextRun("CONSORT-style accounting of wild-type and knockout animals from implantation at 3 months through the six EEG timepoints (3, 4, 6, 7, 9, 12 months) and the 10-month behavioural battery, with per-timepoint counts and attrition by genotype. Counts reflect animals with usable, video-paired recordings at each session and are a lower bound on contributing animals; values are to be reconciled against the master enrolment log, with reasons for attrition, before submission.")]));

c.push(figure("pac_full_comodulogram_matrix.png", 460));
c.push(rich([new TextRun({text:"Figure S2. Full cortical phase-amplitude coupling matrix. ",bold:true}),new TextRun("Genotype effect size (Cohen\u2019s d, knockout \u2212 wild-type) for every phase band (theta, alpha) against both gamma amplitude bands (low, high) during cortical REM at the principal timepoints; values are small and no cell reaches FDR significance, supporting a frequency-general PAC null.")]));

c.push(figure("pac_power_confound.png", 430));
c.push(rich([new TextRun({text:"Figure S3. Power-confound check. ",bold:true}),new TextRun("Genotype effect size over time for REM theta power (the PAC phase band) and REM gamma power (the PAC amplitude band); the near-zero gamma-power differences indicate that the PAC null does not arise from a gamma-power confound.")]));

c.push(figure("cv_auc_forest.png", 450));
c.push(figure("auc_permutation_null.png", 380));
c.push(rich([new TextRun({text:"Figure S4. Cross-validated classification. ",bold:true}),new TextRun("Forest plot of in-sample, leave-one-out, and repeated k-fold AUC for the headline features (top), and the label-permutation null distribution for the strongest classifier, 4-month REM relative beta (observed AUC = 0.92, empirical p = 0.004; bottom).")]));

c.push(figure("roc_key_features.png", 430));
c.push(rich([new TextRun({text:"Figure S5. Genotype classification by headline features. ",bold:true}),new TextRun("Receiver-operating-characteristic curves for animal-level genotype classification by each headline EEG feature, with in-sample AUC; the acute 4-month REM beta and theta/delta features and the end-stage beta reversal are the strongest discriminators, while the 3-month aperiodic exponent is near chance.")]));

c.push(figure("staging_sensitivity_heatmap.png", 460));
c.push(figure("state_separation_diagnostic.png", 380));
c.push(rich([new TextRun({text:"Figure S6. Staging-sensitivity and state separation. ",bold:true}),new TextRun("Genotype effect size for each headline REM feature across the 9-point threshold grid (top): the 4-month beta and theta/delta effects remain positive and the 12-month beta effect remains negative throughout, showing the findings are not artifacts of any single staging cutoff. The theta-delta-plane state-separation diagnostic (bottom) provides visual justification for the band-power vigilance-state classification.")]));

c.push(figure("sleep_state_validation_motion.png", 460));
c.push(rich([new TextRun({text:"Figure S7. Validation of EEG-defined REM using synchronous video. ",bold:true}),new TextRun("Left: video motion energy (an electromyography surrogate) by vigilance state, with wakefulness partitioned into quiet and active (upper movement quartile). REM-classified epochs are immobile and far below active wakefulness (Cohen\u2019s d = \u22121.28), the contrast relevant to the active-wake confound; 91.6% of REM epochs were behaviourally immobile across the full cohort (n = 20,436). Right: hippocampal CA3 theta/delta ratio by state, greatest during REM (REM vs wake d = +0.38; ~6.3 Hz theta peak). Together with physiological REM proportion (7\u201310% of total time) and low wake-to-REM transition probability (0.07), these confirm that the EEG-defined REM state is behaviourally quiescent and hippocampally appropriate rather than misclassified active wake.")]));

// ---- Split content into MAIN manuscript and SUPPLEMENTARY materials ----
// SUPP_START is recorded where the "Supplementary Materials" heading is pushed.
let splitIdx = (typeof SUPP_START === "number" && SUPP_START >= 0) ? SUPP_START : c.length;
const mainContent = c.slice(0, splitIdx);
const suppContent = c.slice(splitIdx);

const styleBlock = {default:{document:{run:{font:ARIAL,size:22}}},paragraphStyles:[
    {id:"Heading1",name:"Heading 1",basedOn:"Normal",next:"Normal",quickFormat:true,run:{size:28,bold:true,font:ARIAL},paragraph:{spacing:{before:280,after:160},outlineLevel:0}},
    {id:"Heading2",name:"Heading 2",basedOn:"Normal",next:"Normal",quickFormat:true,run:{size:24,bold:true,font:ARIAL},paragraph:{spacing:{before:200,after:120},outlineLevel:1}}]};
const pageProps = {properties:{page:{size:{width:12240,height:15840},margin:{top:1440,right:1440,bottom:1440,left:1440}}},
    footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({children:[PageNumber.CURRENT],size:18})]})]})}};

function buildDoc(children){
  return new Document({styles:styleBlock, sections:[{...pageProps, children}]});
}

// Combined (everything) — kept for convenience
const docAll = buildDoc(c);
Packer.toBuffer(docAll).then(b=>{fs.writeFileSync("/home/claude/manuscript/manuscript_v2_brain.docx",b);console.log("written combined");});

// Main manuscript only
const docMain = buildDoc(mainContent);
Packer.toBuffer(docMain).then(b=>{fs.writeFileSync("/home/claude/manuscript/manuscript_v2_brain_MAIN.docx",b);console.log("written main");});

// Supplementary materials only (prepend a title page)
const suppTitle = new Paragraph({spacing:{after:240},children:[new TextRun({
  text:"Supplementary Materials: A biphasic trajectory of cortical and hippocampal network dysfunction during REM sleep in C9orf72-deficient mice",
  bold:true,size:28,font:ARIAL})]});
const docSupp = buildDoc([suppTitle, ...suppContent]);
Packer.toBuffer(docSupp).then(b=>{fs.writeFileSync("/home/claude/manuscript/manuscript_v2_brain_SUPPLEMENTARY.docx",b);console.log("written supplementary");});
